### PR TITLE
Merging connect kwargs and init kwargs with priority

### PR DESCRIPTION
**Pull request by sallory**
#14 

Please feel free to correct me and ask me to fix/add something.

### CODE REVIEW

**Comment by Lancetnik** [comment]
Hi there! It's a good starting point, but I am thinking about merging args and kwargs both

```python
Broker("smth-url")
Broker.connect(url="smth-url")
```
Should be a valid case, but in your code it leads to exception.
Take a look [here](https://github.com/Lancetnik/FastDepends/blob/main/fast_depends/utils.py#L23), it can be helpful to merge all args and kwargs to one dict

**Comment by sallory** [comment]
Thanks for your comment.
I got you, I will take a look at your code and update this pr soon

**Comment by Lancetnik** [comment]
Do you need some help with this?

**Comment by sallory** [comment]
Hi, didn't have time for this task.
But I'm thinking about how to detect the arguments list for the particular broker.
Like I want to use your `args_to_kwargs`, but we don't know the list of arguments.

The first approach would be, storing the arguments list in the broker class:

```
class RabbitBroker:
    __connect_arguments: list = ['url']
    
    
class KafkaBroker:
   __connect_arguments: list = ['bootstrap_servers']
```

and we can do like this:
```
class BrokerUsecase:
        async def connect(self, *args: Any, **kwargs: Any) -> Any:
            if self._connection is None:
                _kwargs = args_to_kwargs(self.__connect_arguments, args, kwargs)
                self._connection = await self._connect(**_kwargs)
            return self._connection    
```

What do you think?

**Comment by Lancetnik** [comment]
I suppose, you should move all broker __init__ arguments from .pyi to real .py files and get information about them by inspect module.

**Comment by sallory** [comment]
Hi @Lancetnik 
Updated the pr

- changed the signature of `_connect` method to accept only `kwargs`
- the list of key-word only params changed in some of .pyi files and Brokers' `__init__` methods, because for example nats.connect wants only 1 pos argument (servers)

**Comment by sallory** [comment]
@Lancetnik For sure. If I will have time, I would like to help you meet your goals with this project

**Pull request merged**
